name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so git describe can access tags

      - name: Install packaging deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Install ncurses
        if: runner.os == 'macOS'
        run: brew install ncurses

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Install to staging
        run: cmake --install build --prefix dist

      - name: Copy install script
        run: cp scripts/install.sh dist/install.sh && chmod +x dist/install.sh

      - name: Create tarball
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          tar -czf json-view-$VERSION-${{ matrix.os }}.tar.gz -C dist .

      - name: Build DEB and RPM
        if: runner.os == 'Linux'
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Build static RPM
        if: runner.os == 'Linux'
        run: scripts/build-static-rpm.sh

      - name: Build Amazon Linux 2023 RPM
        if: runner.os == 'Linux'
        run: |
          docker run --rm -v $PWD:/src -w /src amazonlinux:2023 \
            bash -lc 'dnf install -y cmake gcc gcc-c++ make rpm-build tar && scripts/build-al2023-rpm.sh'
          VERSION=${GITHUB_REF_NAME#v}
          mv json-view-${VERSION}-Linux.rpm json-view-${VERSION}-amazonlinux2023.rpm

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            json-view-*.tar.gz
            build/*.deb
            build/*.rpm
            json-view-static-*.rpm
            json-view-*amazonlinux2023*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
